Update app-deploy.yml

diff --git a/.github/workflows/app-deploy.yml b/.github/workflows/app-deploy.yml
--- a/.github/workflows/app-deploy.yml
+++ b/.github/workflows/app-deploy.yml
@@ -31,128 +31,128 @@ jobs:
           echo "can_deploy=$CAN_DEPLOY" >> $GITHUB_OUTPUT
 
 
-  ##########################
-  # Deploy Worker
-  ##########################
-  deploy_worker:
-    needs: pre-check
-    if: needs.pre-check.outputs.can_deploy == 'true'
-    runs-on: self-hosted
-    environment: production
-    env:
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      AWS_REGION: us-east-1
-      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
-      IMAGE_REPO: multi-cloud-cost-and-service-status-dashboard-repo
-      SSM_PARAM_NAME: myapp_database_credentials
-      S3_JSON_PATH: s3://multi-cloud-cost-and-service-status-dashboard/infra/multi-cloud-dashboard-outputs.json
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  # ##########################
+  # # Deploy Worker
+  # ##########################
+  # deploy_worker:
+  #   needs: pre-check
+  #   if: needs.pre-check.outputs.can_deploy == 'true'
+  #   runs-on: self-hosted
+  #   environment: production
+  #   env:
+  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #     AWS_REGION: us-east-1
+  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     IMAGE_REPO: multi-cloud-cost-and-service-status-dashboard-repo
+  #     SSM_PARAM_NAME: myapp_database_credentials
+  #     S3_JSON_PATH: s3://multi-cloud-cost-and-service-status-dashboard/infra/multi-cloud-dashboard-outputs.json
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ env.DOCKERHUB_USERNAME }}
-          password: ${{ env.DOCKERHUB_TOKEN }}
+  #     - name: Log in to Docker Hub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ env.DOCKERHUB_USERNAME }}
+  #         password: ${{ env.DOCKERHUB_TOKEN }}
 
-      - name: Fetch DB credentials from SSM
-        run: |
-          PARAM_VALUE=$(aws ssm get-parameter --name "$SSM_PARAM_NAME" --with-decryption --query "Parameter.Value" --output text)
-          DB_USER=$(echo $PARAM_VALUE | jq -r '.username')
-          DB_PASS=$(echo $PARAM_VALUE | jq -r '.password')
-          echo "DB_USER=$DB_USER" >> $GITHUB_ENV
-          echo "DB_PASS=$DB_PASS" >> $GITHUB_ENV
-      - name: Print payload for debugging
-        run: |
-          echo "Backend: ${{ github.event.client_payload.backend }}"
-          echo "Worker: ${{ github.event.client_payload.worker }}"
-          echo "Frontend: ${{ github.event.client_payload.frontend }}"
+  #     - name: Fetch DB credentials from SSM
+  #       run: |
+  #         PARAM_VALUE=$(aws ssm get-parameter --name "$SSM_PARAM_NAME" --with-decryption --query "Parameter.Value" --output text)
+  #         DB_USER=$(echo $PARAM_VALUE | jq -r '.username')
+  #         DB_PASS=$(echo $PARAM_VALUE | jq -r '.password')
+  #         echo "DB_USER=$DB_USER" >> $GITHUB_ENV
+  #         echo "DB_PASS=$DB_PASS" >> $GITHUB_ENV
+  #     - name: Print payload for debugging
+  #       run: |
+  #         echo "Backend: ${{ github.event.client_payload.backend }}"
+  #         echo "Worker: ${{ github.event.client_payload.worker }}"
+  #         echo "Frontend: ${{ github.event.client_payload.frontend }}"
 
 
-      - name: Deploy Worker
-        id: deploy_worker
-        run: |
-          PEM_PATH=~/ssh-keys/multi-cloud-cost-and-service-status-key.pem
-          WORKER_IMAGE="${{ github.event.client_payload.worker }}"
+  #     - name: Deploy Worker
+  #       id: deploy_worker
+  #       run: |
+  #         PEM_PATH=~/ssh-keys/multi-cloud-cost-and-service-status-key.pem
+  #         WORKER_IMAGE="${{ github.event.client_payload.worker }}"
       
-          echo "Downloading worker output JSON from S3..."
-          aws s3 cp "$S3_JSON_PATH" worker-outputs.json
+  #         echo "Downloading worker output JSON from S3..."
+  #         aws s3 cp "$S3_JSON_PATH" worker-outputs.json
       
-          DB_HOST=$(jq -r '.db.endpoint | split(":")[0]' worker-outputs.json)
-          DB_NAME=$(jq -r '.db.name' worker-outputs.json)
-          INSTANCE_IDS=$(jq -r '.ec2_instance_ids[]' worker-outputs.json)
+  #         DB_HOST=$(jq -r '.db.endpoint | split(":")[0]' worker-outputs.json)
+  #         DB_NAME=$(jq -r '.db.name' worker-outputs.json)
+  #         INSTANCE_IDS=$(jq -r '.ec2_instance_ids[]' worker-outputs.json)
       
-          echo "Database host: $DB_HOST"
-          echo "Database name: $DB_NAME"
-          echo "Instances to deploy: $INSTANCE_IDS"
+  #         echo "Database host: $DB_HOST"
+  #         echo "Database name: $DB_NAME"
+  #         echo "Instances to deploy: $INSTANCE_IDS"
       
-          for ID in $INSTANCE_IDS; do
-            IP=$(aws ec2 describe-instances --instance-ids $ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
-            echo "------------------------------------------------------------"
-            echo "Deploying worker on instance ID: $ID, IP: $IP"
+  #         for ID in $INSTANCE_IDS; do
+  #           IP=$(aws ec2 describe-instances --instance-ids $ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
+  #           echo "------------------------------------------------------------"
+  #           echo "Deploying worker on instance ID: $ID, IP: $IP"
             
-            OLD_CONTAINER_PRESENT=$(ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
-              "sudo docker ps -a --filter 'name=worker' --format '{{.Names}}' | grep -w worker || true")
-            if [ -z "$OLD_CONTAINER_PRESENT" ]; then
-              echo "No existing worker container found on $IP. First deployment."
-              PREV_IMAGE="$WORKER_IMAGE"
-            else
-              PREV_IMAGE=$(ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
-                "sudo docker inspect --format='{{.Config.Image}}' worker || echo '$WORKER_IMAGE'")
-              echo "Found existing worker container on $IP. Previous image: $PREV_IMAGE"
-            fi
+  #           OLD_CONTAINER_PRESENT=$(ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
+  #             "sudo docker ps -a --filter 'name=worker' --format '{{.Names}}' | grep -w worker || true")
+  #           if [ -z "$OLD_CONTAINER_PRESENT" ]; then
+  #             echo "No existing worker container found on $IP. First deployment."
+  #             PREV_IMAGE="$WORKER_IMAGE"
+  #           else
+  #             PREV_IMAGE=$(ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
+  #               "sudo docker inspect --format='{{.Config.Image}}' worker || echo '$WORKER_IMAGE'")
+  #             echo "Found existing worker container on $IP. Previous image: $PREV_IMAGE"
+  #           fi
       
-            echo "Cleaning any old worker_new container..."
-            ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
-              "sudo docker rm -f worker_new >/dev/null 2>&1 || true"
+  #           echo "Cleaning any old worker_new container..."
+  #           ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
+  #             "sudo docker rm -f worker_new >/dev/null 2>&1 || true"
       
-            echo "Logging in to Docker Hub and pulling image: $WORKER_IMAGE"
-            ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
-              "echo '$DOCKERHUB_TOKEN' | docker login -u '$DOCKERHUB_USERNAME' --password-stdin; \
-               docker pull $WORKER_IMAGE"
+  #           echo "Logging in to Docker Hub and pulling image: $WORKER_IMAGE"
+  #           ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
+  #             "echo '$DOCKERHUB_TOKEN' | docker login -u '$DOCKERHUB_USERNAME' --password-stdin; \
+  #              docker pull $WORKER_IMAGE"
       
-            echo "Starting new worker container..."
-            ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
-              "docker run -d --name worker_new \
-                -e AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' \
-                -e AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' \
-                -e AWS_REGION='$AWS_REGION' \
-                -e DB_HOST='$DB_HOST' \
-                -e DB_NAME='$DB_NAME' \
-                -e DB_USER='$DB_USER' \
-                -e DB_PASS='$DB_PASS' \
-                -e POLL_INTERVAL_SECONDS=60000 \
-                $WORKER_IMAGE"
+  #           echo "Starting new worker container..."
+  #           ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
+  #             "docker run -d --name worker_new \
+  #               -e AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' \
+  #               -e AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' \
+  #               -e AWS_REGION='$AWS_REGION' \
+  #               -e DB_HOST='$DB_HOST' \
+  #               -e DB_NAME='$DB_NAME' \
+  #               -e DB_USER='$DB_USER' \
+  #               -e DB_PASS='$DB_PASS' \
+  #               -e POLL_INTERVAL_SECONDS=60000 \
+  #               $WORKER_IMAGE"
       
-            echo "Waiting 30 seconds for the container to start..."
-            sleep 30
+  #           echo "Waiting 30 seconds for the container to start..."
+  #           sleep 30
       
-            STATUS=$(ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
-              "sudo docker ps --filter 'name=worker_new' --filter 'status=running' | grep worker_new >/dev/null 2>&1; echo \$?")
+  #           STATUS=$(ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
+  #             "sudo docker ps --filter 'name=worker_new' --filter 'status=running' | grep worker_new >/dev/null 2>&1; echo \$?")
             
-            if [ "$STATUS" -ne 0 ]; then
-              echo "Worker rollout FAILED on $IP. Printing last 200 logs:"
-              ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
-                "sudo docker logs --tail=200 worker_new || true; sudo docker rm -f worker_new || true"
-              echo "Worker rollout failed. Old worker kept on $IP."
-              exit 1
-            else
-              echo "Worker rollout SUCCESS on $IP."
-              echo "worker_current_image=$WORKER_IMAGE" >> $GITHUB_OUTPUT
-              echo "worker_previous_image=$PREV_IMAGE" >> $GITHUB_OUTPUT
-              echo "worker_status=success" >> $GITHUB_OUTPUT
-            fi
-          done
+  #           if [ "$STATUS" -ne 0 ]; then
+  #             echo "Worker rollout FAILED on $IP. Printing last 200 logs:"
+  #             ssh -o StrictHostKeyChecking=no -i "$PEM_PATH" ec2-user@"$IP" \
+  #               "sudo docker logs --tail=200 worker_new || true; sudo docker rm -f worker_new || true"
+  #             echo "Worker rollout failed. Old worker kept on $IP."
+  #             exit 1
+  #           else
+  #             echo "Worker rollout SUCCESS on $IP."
+  #             echo "worker_current_image=$WORKER_IMAGE" >> $GITHUB_OUTPUT
+  #             echo "worker_previous_image=$PREV_IMAGE" >> $GITHUB_OUTPUT
+  #             echo "worker_status=success" >> $GITHUB_OUTPUT
+  #           fi
+  #         done
 
 
   ##########################
   # Deploy Backend
   ##########################
   deploy_backend:
-    needs: deploy_worker
+    needs: pre-check
     runs-on: self-hosted
     environment: production
     env:
