Update app-pipeline.yml

diff --git a/.github/workflows/app-pipeline.yml b/.github/workflows/app-pipeline.yml
--- a/.github/workflows/app-pipeline.yml
+++ b/.github/workflows/app-pipeline.yml
@@ -69,44 +69,42 @@ jobs:
           docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-latest
           docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-${VERSION}
 
-  deploy-worker:
+  # ===== JOB 2: Deployment Check & Run Worker =====
+  deployment-check:
     needs: build-and-push-dockerhub
     runs-on: self-hosted
     env:
-      INFRA_JSON_PATH: ./infra.json
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_REGION: us-east-1
       S3_JSON_PATH: s3://multi-cloud-cost-and-service-status-dashboard/infra/multi-cloud-dashboard-outputs.json
+      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+      IMAGE_REPO: multi-cloud-cost-and-service-status-dashboard-repo
+      VERSION: v${{ github.run_number }}
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Download Terraform output JSON
+      - name: Verify JSON exists in S3
         run: |
-          aws s3 cp $S3_JSON_PATH $INFRA_JSON_PATH || exit 1
+          echo "Checking JSON file in S3..."
+          if ! aws s3 ls "$S3_JSON_PATH" ; then
+            echo "JSON file not found in S3. Check with infra team."
+          else
+            echo "JSON file exists."
 
-      - name: Verify JSON file exists
+      - name: Pull Worker Docker Image
         run: |
-          if [ ! -f "$INFRA_JSON_PATH" ]; then
-            echo "ERROR: Terraform infra.json not found. Contact infrastructure team."
-            exit 1
-          fi
+          docker pull $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION}
 
-      - name: Extract variables from JSON
-        id: extract
-        run: |
-          DB_HOST=$(jq -r '.db.endpoint' $INFRA_JSON_PATH | cut -d: -f1)
-          DB_NAME=$(jq -r '.db.name' $INFRA_JSON_PATH)
-          AWS_REGION=$(echo "$DB_HOST" | awk -F. '{print $4}')
-          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
-          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
-          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
-          echo "SSM_PARAM_NAME=myapp_database_credentials" >> $GITHUB_ENV
-
-      - name: Run Worker container
+      - name: Run Worker Container
         run: |
           docker run --rm \
             -e AWS_REGION=$AWS_REGION \
-            -e DB_HOST=$DB_HOST \
-            -e DB_NAME=$DB_NAME \
-            -e SSM_PARAM_NAME=$SSM_PARAM_NAME \
-            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:worker-latest
+            -e SSM_PARAM_NAME=myapp_database_credentials \
+            -e DB_NAME=appdb \
+            -e POLL_INTERVAL_SECONDS=600 \
+            $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION}
+
+
